src/main/java/org/jboss/as/quickstarts/kitchensink/model/TeamState.java
package org.jboss.as.quickstarts.kitchensink.model;

public enum TeamState {
    ACCEPTED, 
    PENDING, 
    CANCELED
}

src/main/java/org/jboss/as/quickstarts/kitchensink/controller/ContestController.java
package org.jboss.as.quickstarts.kitchensink.controller;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

import javax.annotation.PostConstruct;
import javax.enterprise.inject.Produces;
import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;
import javax.faces.view.ViewScoped;
import javax.inject.Inject;
import javax.inject.Named;

import org.jboss.as.quickstarts.kitchensink.data.ContestListProducer;
import org.jboss.as.quickstarts.kitchensink.data.MemberListProducer;
import org.jboss.as.quickstarts.kitchensink.model.Contest;
import org.jboss.as.quickstarts.kitchensink.model.Member;
import org.jboss.as.quickstarts.kitchensink.service.ContestRegistration;

@Named
@ViewScoped
public class ContestController implements Serializable {

    public static final String BR2_MESSAGE = "BR2. team/contest changes are allowed only if contest flag indicates it is writtable";
	
    @Inject
    private FacesContext facesContext;
    
    @Inject
    private ContestRegistration contestRegistration;
    
    @Produces
    @Named
    private Contest newContest;
    
    @Inject
    MemberListProducer mlp;
    
    @Inject
    ContestListProducer clp;

    @PostConstruct
    public void initNewContest() {
        newContest = new Contest();
    }
    
    public void saveContest() throws Exception {
    	if(!contestRegistration.checkCanEdit(newContest)) {
            FacesMessage m = new FacesMessage(FacesMessage.SEVERITY_ERROR, BR2_MESSAGE, "Registration unsuccessful");
            facesContext.addMessage(null, m);
            return;
    	}
        try {
            contestRegistration.save(newContest);
            FacesMessage m = new FacesMessage(FacesMessage.SEVERITY_INFO, "Registered!", "Registration successful");
            facesContext.addMessage(null, m);
            initNewContest();
        } catch (Exception e) {
            String errorMessage = getRootErrorMessage(e);
            FacesMessage m = new FacesMessage(FacesMessage.SEVERITY_ERROR, errorMessage, "Registration unsuccessful");
            facesContext.addMessage(null, m);
        }
    }
    
    public List<Member> eligibleManagers(String query) {
        List<Member> results = new ArrayList<Member>();
        for (Member member : mlp.getMembers()) {
            if(member.getName().toLowerCase().startsWith(query)) {
                results.add(member);
            }
        }
        return results;
    }
    
    public List<Contest> availableContests(String query) {
        List<Contest> results = new ArrayList<Contest>();
        for (Contest contest : clp.getContests()) {
            if(contest.getName().toLowerCase().startsWith(query)) {
                results.add(contest);
            }
        }
        return results;
    }

    public Boolean isEditable(Contest contest) {
        return contestRegistration.checkCanEdit(contest);
    }
    
    private String getRootErrorMessage(Exception e) {
        // Default to general error message that registration failed.
        String errorMessage = "Registration failed. See server log for more information";
        if (e == null) {
            // This shouldn't happen, but return the default messages
            return errorMessage;
        }

        // Start with the exception and recurse to find the root cause
        Throwable t = e;
        while (t != null) {
            // Get the message from the Throwable class instance
            errorMessage = t.getLocalizedMessage();
            t = t.getCause();
        }
        // This is the root cause message
        return errorMessage;
    }
}

src/main/java/org/jboss/as/quickstarts/kitchensink/controller/ContestDetailController.java
package org.jboss.as.quickstarts.kitchensink.controller;

import java.io.Serializable;

import javax.annotation.PostConstruct;
import javax.faces.application.FacesMessage;
import javax.faces.bean.RequestScoped;
import javax.faces.context.FacesContext;
import javax.inject.Inject;
import javax.inject.Named;

import org.jboss.as.quickstarts.kitchensink.model.Contest;
import org.jboss.as.quickstarts.kitchensink.model.Team;
import org.jboss.as.quickstarts.kitchensink.model.TeamState;
import org.jboss.as.quickstarts.kitchensink.repositories.DeltaContestRepository;
import org.jboss.as.quickstarts.kitchensink.service.ContestRegistration;
import org.jboss.as.quickstarts.kitchensink.service.TeamRegistration;

@Named
@RequestScoped
public class ContestDetailController implements Serializable {
    
    public static final String BR2_MESSAGE = "BR2. team/contest changes are allowed only if contest flag indicates it is writtable";

    
    @Named
    private Long selected;

    @Named
    private Contest selectedContest;
    
    @Inject
    private FacesContext facesContext;

    @Inject
    private TeamRegistration teamRegistration;

    @Inject
    private ContestRegistration contestRegistration;

    @Inject
    private DeltaContestRepository dcr;
    
    @PostConstruct
    public void initContest() {
        selected = Long.parseLong(facesContext.getExternalContext().getRequestParameterMap().get("contest_id"));
        selectedContest = dcr.findOptionalById(selected);
    }
    
    public void saveTeam(Team team) throws Exception {
        if(!contestRegistration.checkCanEdit(team.getContest())) {
            FacesMessage m = new FacesMessage(FacesMessage.SEVERITY_ERROR, BR2_MESSAGE, "Changes unsuccessful");
            facesContext.addMessage(null, m);
            return;
        }
        try {
            teamRegistration.save(team);
            FacesMessage m = new FacesMessage(FacesMessage.SEVERITY_INFO, "Saved!", "Changes successful");
            facesContext.addMessage(null, m);
        } catch (Exception e) {
            String errorMessage = getRootErrorMessage(e);
            FacesMessage m = new FacesMessage(FacesMessage.SEVERITY_ERROR, errorMessage, "Registration unsuccessful");
            facesContext.addMessage(null, m);
        }
    }
    
    public Boolean isEnabled(Long id) {
        Contest c = dcr.findOptionalById(id);
        if (c == null) {
            return false;
        }
        return contestRegistration.checkCanEdit(c);
    }
    
//    public void onStateChange(Team team) throws Exception {
//        saveTeam(team);
//    }
    
    private String getRootErrorMessage(Exception e) {
        // Default to general error message that registration failed.
        String errorMessage = "Registration failed. See server log for more information";
        if (e == null) {
            // This shouldn't happen, but return the default messages
            return errorMessage;
        }

        // Start with the exception and recurse to find the root cause
        Throwable t = e;
        while (t != null) {
            // Get the message from the Throwable class instance
            errorMessage = t.getLocalizedMessage();
            t = t.getCause();
        }
        // This is the root cause message
        return errorMessage;
    }

    public Contest getSelectedContest() {
        return selectedContest;
    }

    public void setSelectedContest(Contest selectedContest) {
        this.selectedContest = selectedContest;
    }
    
    public TeamState[] getPossibleStates() {
        TeamState[] states = {TeamState.PENDING, TeamState.ACCEPTED, TeamState.CANCELED };
        return states;
    }
}

src/main/java/org/jboss/as/quickstarts/kitchensink/controller/MemberController.java
/*
 * JBoss, Home of Professional Open Source
 * Copyright 2015, Red Hat, Inc. and/or its affiliates, and individual
 * contributors by the @authors tag. See the copyright.txt in the
 * distribution for a full listing of individual contributors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * http://www.apache.org/licenses/LICENSE-2.0
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.jboss.as.quickstarts.kitchensink.controller;

import java.io.Serializable;

import javax.annotation.PostConstruct;
import javax.enterprise.inject.Produces;
import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;
import javax.faces.view.ViewScoped;
import javax.inject.Inject;
import javax.inject.Named;

import org.jboss.as.quickstarts.kitchensink.model.Member;
import org.jboss.as.quickstarts.kitchensink.service.MemberRegistration;

// The @Model stereotype is a convenience mechanism to make this a request-scoped bean that has an
// EL name
// Read more about the @Model stereotype in this FAQ:
// http://www.cdi-spec.org/faq/#accordion6
@Named
@ViewScoped
public class MemberController implements Serializable {

    @Inject
    private FacesContext facesContext;

    @Inject
    private MemberRegistration memberRegistration;

    @Produces
    @Named
    private Member newMember;
        
    @PostConstruct
    public void initNewMember() {
        newMember = new Member();
    }    
    
    public void saveMember() throws Exception {
        Boolean updateExisting = newMember != null && newMember.getId() != null;
        try {
            memberRegistration.save(newMember);
            FacesMessage m = new FacesMessage(FacesMessage.SEVERITY_INFO, 
                    updateExisting ? "Updated!" : "Registered!", 
                    updateExisting ? "Update successful" :" Registration successful");
            facesContext.addMessage(null, m);
            initNewMember();
        } catch (Exception e) {
            String errorMessage = getRootErrorMessage(e);
            FacesMessage m = new FacesMessage(FacesMessage.SEVERITY_ERROR, 
                    errorMessage, 
                    updateExisting ? "Update unsuccessful" : "Registration unsuccessful");
            facesContext.addMessage(null, m);
        }
    }

    public void unregister(Member member) throws Exception {
        try {
            memberRegistration.remove(member);
            FacesMessage m = new FacesMessage(FacesMessage.SEVERITY_INFO, "Deleted!", "Deleted successful");
            facesContext.addMessage(null, m);
        } catch (Exception e) {
            String errorMessage = getRootErrorMessage(e);
            FacesMessage m = new FacesMessage(FacesMessage.SEVERITY_ERROR, errorMessage, "Deleted unsuccessful");
            facesContext.addMessage(null, m);
        }
    }
    
    private String getRootErrorMessage(Exception e) {
        // Default to general error message that registration failed.
        String errorMessage = "Registration failed. See server log for more information";
        if (e == null) {
            // This shouldn't happen, but return the default messages
            return errorMessage;
        }

        // Start with the exception and recurse to find the root cause
        Throwable t = e;
        while (t != null) {
            // Get the message from the Throwable class instance
            errorMessage = t.getLocalizedMessage();
            t = t.getCause();
        }
        // This is the root cause message
        return errorMessage;
    }

    public Member getNewMember() {
        return newMember;
    }

    public void setNewMember(Member oldNewMember) {
        newMember = oldNewMember;
    }

}

src/main/java/org/jboss/as/quickstarts/kitchensink/controller/TeamController.java
package org.jboss.as.quickstarts.kitchensink.controller;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

import javax.annotation.PostConstruct;
import javax.enterprise.inject.Produces;
import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;
import javax.faces.view.ViewScoped;
import javax.inject.Inject;
import javax.inject.Named;

import org.jboss.as.quickstarts.kitchensink.data.ContestListProducer;
import org.jboss.as.quickstarts.kitchensink.data.MemberListProducer;
import org.jboss.as.quickstarts.kitchensink.model.Contest;
import org.jboss.as.quickstarts.kitchensink.model.Member;
import org.jboss.as.quickstarts.kitchensink.model.Team;
import org.jboss.as.quickstarts.kitchensink.service.TeamRegistration;

@Named
@ViewScoped
public class TeamController implements Serializable {

    public static final String BR1_MESSAGE = "BR1. registration allowed only to team with a distinct name, "
            + "1 coach and 3 team members, that are distinct; only when the contest has available capacity "
            + "and team members are younger 24 years; while team members cannot be also in a different team"
            + " in the contest (unless promoted).";

    public static final String BR2_MESSAGE = "BR2. team/contest changes are allowed only if contest flag indicates it is writtable";
    
    
    @Inject
    private FacesContext facesContext;
    
    @Inject
    private TeamRegistration teamRegistration;
    
    @Inject
    MemberListProducer mlp;

    @Inject
    ContestListProducer clp;

    @Produces
    @Named
    private Team newTeam;

    public Team getNewTeam() {
        return newTeam;
    }

    public void setNewTeam(Team newTeam) {
        this.newTeam = newTeam;
    }
    
    @PostConstruct
    public void initNewTeam() {
        newTeam = new Team();
    }
  
    public void saveTeam() {
    	
        if (!teamRegistration.checkTeamEligibility(newTeam)) {
            FacesMessage m = new FacesMessage(FacesMessage.SEVERITY_ERROR, BR1_MESSAGE, "Registration unsuccessful");
            facesContext.addMessage(null, m);
            return;
        }
        if (!teamRegistration.checkCanEdit(newTeam)) {
            FacesMessage m = new FacesMessage(FacesMessage.SEVERITY_ERROR, BR2_MESSAGE, "Registration unsuccessful");
            facesContext.addMessage(null, m);
            return;
        }
        try {
            teamRegistration.save(newTeam);
            FacesMessage m = new FacesMessage(FacesMessage.SEVERITY_INFO, "Registered!", "Registration successful");
            facesContext.addMessage(null, m);
            initNewTeam();
        } catch (Exception e) {
            String errorMessage = getRootErrorMessage(e);
            FacesMessage m = new FacesMessage(FacesMessage.SEVERITY_ERROR, errorMessage, "Registration unsuccessful");
            facesContext.addMessage(null, m);
        }
    }
    
    public List<Member> availableMembers(String query) {
        List<Member> results = new ArrayList<Member>();
        for (Member member : mlp.getMembers()) {
            if(member.getName().toLowerCase().startsWith(query)) {
                results.add(member);
            }
        }
        return results;
    }

    public List<Contest> availableContests(String query) {
        List<Contest> results = new ArrayList<Contest>();
        for (Contest contest : clp.getContests()) {
            if(contest.getName().toLowerCase().startsWith(query)) {
                results.add(contest);
            }
        }
        return results;
    }
    
    private String getRootErrorMessage(Exception e) {
        // Default to general error message that registration failed.
        String errorMessage = "Registration failed. See server log for more information";
        if (e == null) {
            // This shouldn't happen, but return the default messages
            return errorMessage;
        }

        // Start with the exception and recurse to find the root cause
        Throwable t = e;
        while (t != null) {
            // Get the message from the Throwable class instance
            errorMessage = t.getLocalizedMessage();
            t = t.getCause();
        }
        // This is the root cause message
        return errorMessage;
    }
}

src/main/webapp/contestDetail.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:p="http://primefaces.org/ui"
	template="/WEB-INF/templates/default.xhtml">
	<ui:define name="content">
		<script type="text/javascript">
            var websocket = null;

            function connect() {
                var wsProtocol = window.location.protocol == "https:" ? "wss" : "ws";
                var wsURI = wsProtocol + '://' + window.location.host + '/kitchensink-pg/contestDetail.xhtml';
                websocket = new WebSocket(wsURI);

                websocket.onopen = function() {
                    document.getElementById("loading").innerText = "Connected to teams' states";
                    fixStates();
                };
                websocket.onmessage = function(event) {
                    console.log("recieved");
                    updateStates(String(event.data));
                };
                websocket.onerror = function(event) {
                    
                };
                websocket.onclose = function() {
                    
                };
            }

            function disconnect() {
                if (websocket !== null) {
                    websocket.close();
                    websocket = null;
                }
                message.setAttribute("class", "message");
                message.value = 'WebSocket closed.';
                // log the event
            }

            function sendMessage(message) {
                if (websocket !== null) {
                    var content = message;
                    websocket.send(content);
                } else {
                    displayMessage('WebSocket connection is not established. Please click the Open Connection button.', 'error');
                }
            }

            function displayMessage(data, style) {
                var message = document.getElementById('loading');
                message.setAttribute("class", style);
                message.value = data;
            }

            function displayStatus(status) {
                var currentStatus = document.getElementById('currentstatus');
                currentStatus.value = status;
            }

            function fixStates(){
                let states = document.getElementsByClassName("hiddenState");
                let realEstates = document.getElementsByClassName("realState");
                var i = 0;
                while(i != realEstates.length){
                    realEstates[i].value = states[i].innerHTML;
                    i++;
                }
                
            }

            function selected(ev){
                let message = ev.target.id + ", " + ev.target.value;
                console.log(message);
                sendMessage(message);
                sendIt(message);
            }

            function sendIt(message){
                var xhttp = new XMLHttpRequest();

                xhttp.open("POST", "/kitchensink-pg/rest/members/WhyTeamChange");
                xhttp.send(message);
            }

            function updateStates(toUpdate){
                var id = "";
                var i = 0;
                var yes = false;
                while(i != toUpdate.length){
                    if(toUpdate[i] == ','){
                      	i++;i++;
                      	yes = true;
                      	break;
                      	
                    }
                    id += toUpdate[i];
                    i++;
                }
				if(!yes){
					return;
				}

				var state = "";
                while(i != toUpdate.length){
                    state += toUpdate[i];
                    i++;
                }
                document.getElementById(id).value = state;
                
                
                
         	}
            
            window.onload = function(){
               	connect();
                };

              

        </script>
		<f:metadata>
			<f:viewParam name="contest_id" value="#{selected}" />
		</f:metadata>
		<h1>Contest</h1>
		<h2>Details for #{contestDetailController.selectedContest.name}</h2>
		<p:messages styleClass="messages" errorClass="invalid"
			infoClass="valid" warnClass="warning" globalOnly="true" />

		<p id="loading">Loading connection</p>
		<h:form id="registeredTeamsForm" rendered="#{contestDetailController.isEnabled(selected)}">
			<p:dataTable id="dtable" var="_team"
				value="#{contestDetailController.selectedContest.teams}"
				rendered="#{not empty contestDetailController.selectedContest.teams}">

				<f:facet name="header">
            Teams' Status
        </f:facet>

				<p:column headerText="Name">
            #{_team.name}
        </p:column>

				<p:column headerText="State">
					<span class="hiddenState" id="hiddenStatus#{_team.id}"
						style="display: none;">#{_team.state}</span>
					<select class="realState" onchange="selected(event);"
						id="#{_team.id}">
						<option value="#{contestDetailController.possibleStates[0]}">#{contestDetailController.possibleStates[0]}</option>
						<option value="#{contestDetailController.possibleStates[1]}">#{contestDetailController.possibleStates[1]}</option>
						<option value="#{contestDetailController.possibleStates[2]}">#{contestDetailController.possibleStates[2]}</option>

					</select>
				</p:column>


			</p:dataTable>
		</h:form>
	</ui:define>
</ui:composition>

src/main/webapp/contestRegistration.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
    xmlns:ui="http://java.sun.com/jsf/facelets"
    xmlns:f="http://java.sun.com/jsf/core"
    xmlns:h="http://java.sun.com/jsf/html"
    xmlns:p="http://primefaces.org/ui"
    template="/WEB-INF/templates/default.xhtml">
    <ui:define name="content">
    	<h1>Contest Registration</h1>
    	<h:form id="contestReg">
    	<h2>Register Contest</h2>
    		<p:panelGrid columns="2">
    			<p:outputLabel value="Name:" for="name"/>
    			<p:inputText id="name" value="#{newContest.name}"/>
    			
    			<p:outputLabel value="Date:" for="contestDate"/>
    			<p:calendar id="contestDate" value="#{newContest.contestDate}"/>
    			
    			<p:outputLabel value="Registration From:" for="registrationFrom"/>
    			<p:calendar id="registrationFrom" value="#{newContest.registrationFrom}"/>
    			
    			<p:outputLabel value="Registration To:" for="registrationTo"/>
    			<p:calendar id="registrationTo" value="#{newContest.registrationTo}"/>
    			
    			<p:outputLabel value="Capacity:" for="capacity"/>
    			<p:inputNumber id="capacity" value="#{newContest.capacity}" decimalPlaces="0"/>
    			
    			<p:outputLabel value="Registration Allowed" for="allowRegistration"/>
    			<p:selectBooleanCheckbox id="allowRegistration" value="#{newContest.registrationAllowed}"/>
    			
    			<p:outputLabel value="Managers:" for="manager"/>
    			<p:autoComplete id="manager" dropdown="true" 
    			                completeMethod="#{contestController.eligibleManagers}"
    			                multiple="true" var="onemember" 
    			                itemLabel="#{onemember.name}" itemValue="#{onemember}" value="#{newContest.contestManagers}"
    			                converter="#{memberConverter}"/>

    			<p:outputLabel value="Preliminary Round:" for="prelim"/>
    			<p:autoComplete id="prelim" dropdown="true"
    							completeMethod="#{contestController.availableContests}"
    							multiple="true" var="onecontest" 
    							itemLabel="#{onecontest.name}" itemValue="#{onecontest}" 
    							converter="#{contestConverter}" value="#{newContest.preliminaryRounds}"
    							/>
    			
    			<p:messages styleClass="messages" errorClass="invalid"
                        infoClass="valid" warnClass="warning" globalOnly="true" />
    		</p:panelGrid>
    		<p>
	    		<p:commandButton styleClass="yellow" value="Register Contest" action="#{contestController.saveContest}" ajax="true" update="@form, :contestForm"/>
    		</p>
    	</h:form>
    	
    	<h2>
    		Contests :) :p
    	</h2>
    	<h:form id="contestForm">
    	<p:dataTable id="dtable" var="_contest" value="#{contests}" rendered="#{not empty contests}">
    	
    	<f:facet name="header">
    		Contests
    	</f:facet>
    	
    	<p:column headerText="Name">
    		#{_contest.name}
    	</p:column>
    	
    	<p:column headerText="Attending Teams">
    		#{_contest.teams.size()}
    	</p:column>
    	
    	<p:column headerText="Capacity">
    		#{_contest.capacity}
    	</p:column>
    	
    	<p:column headerText="Teams List">
    		<p:dataList var="_team" value="#{_contest.teams}" type="ordered" paginator="true" rows="5">
    			#{_team.name}
    		</p:dataList>
    	</p:column>
    	
    	<p:column headerText="Details">
    		<p:button outcome="contestDetail.xhtml" value="Details" rendered="#{contestController.isEditable(_contest)}">
    			<f:param name="contest_id" value="#{_contest.id}"/>
    		</p:button>
    	</p:column>
    	
    	</p:dataTable>
    	</h:form>
    	
    			<p>
			<a href="register.xhtml">Register a Team?</a>
		</p>
		<p>
			<a href="index.xhtml">Register a Member?</a>
		</p>
    </ui:define>
</ui:composition>

src/main/webapp/index.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!--
    JBoss, Home of Professional Open Source
    Copyright 2015, Red Hat, Inc. and/or its affiliates, and individual
    contributors by the @authors tag. See the copyright.txt in the
    distribution for a full listing of individual contributors.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at
    http://www.apache.org/licenses/LICENSE-2.0
    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
-->
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:p="http://primefaces.org/ui"
	template="/WEB-INF/templates/default.xhtml">
	<ui:define name="content">

		<!-- Script to handle ajax editing -->

		<h1>Welcome to pink registration service</h1>

		<h:form id="reg">
			<h2>Member Registration</h2>
			<p>Enforces annotation-based constraints defined on the model
				class.</p>
			<p:panelGrid columns="3" columnClasses="titleCell">
				<p:outputLabel for="name" value="Name:" />
				<p:inputText id="name" value="#{newMember.name}" />
				<p:message for="name" errorClass="invalid" />

				<p:outputLabel for="email" value="Email:" />
				<p:inputText id="email" value="#{newMember.email}" />
				<p:message for="email" errorClass="invalid" />

				<p:outputLabel for="phoneNumber" value="Phone #:" />
				<p:inputText id="phoneNumber" value="#{newMember.phoneNumber}" />
				<p:message for="phoneNumber" errorClass="invalid" />

				<p:outputLabel for="bod" value="Birthdate: "/>
				<p:calendar id="bod" value="#{newMember.birthDate}"/>
				<p:message for="bod" errorClass="invalid"/>
			</p:panelGrid>

			<p>
				<p:panelGrid columns="1">
					<p:commandButton id="register" styleClass="yellow register"
						action="#{memberController.saveMember}" value="#{empty newMember.id ? 'Register' : 'Submit edit'}"
						 ajax="true" 
						update="@form,:memberForm" />
					<p:commandButton id="cancelEdit" styleClass="yellow register" 
					    rendered="#{not empty newMember.id}"
                        action="#{memberController.initNewMember}" value="Cancel"
                        update="@form, :memberForm"
                        immediate="true">
                        <p:resetInput target="@form"/>
                    </p:commandButton>
					<p:messages styleClass="messages" errorClass="invalid"
						infoClass="valid" warnClass="warning" globalOnly="true" />
				</p:panelGrid>
			</p>
		</h:form>
		<h2>Members</h2>
		<h:panelGroup rendered="#{empty members}">
			<em>No registered members.</em>
		</h:panelGroup>
		<h:form id="memberForm">
			<p:dataTable id="dtable" var="_member" value="#{members}"
				rendered="#{not empty members}">

				<f:facet name="header">
            	List of Members
            </f:facet>
				<p:column headerText="Id">


					<p class="idField">#{_member.id}</p>
				</p:column>
				<p:column headerText="Name">

					<p>#{_member.name}</p>
				</p:column>
				<p:column headerText="Email">

					<p>#{_member.email}</p>
				</p:column>
				<p:column headerText="Phone #">

					<p>#{_member.phoneNumber}</p>
				</p:column>
				<p:column headerText="REST URL">
					<a href="#{request.contextPath}/rest/members/#{_member.id}">/rest/members/#{_member.id}</a>
				</p:column>
				<p:column headerText="DELETE">

					<p:commandButton id="delete" styleClass="yellow"
					    rendered="#{empty newMember.id}"
						action="#{memberController.unregister(_member)}" value="Del"
						ajax="true" update="@form" />


				</p:column>
				<p:column headerText="EDIT">
					<p:commandButton id="edit" styleClass="yellow"
						action="#{memberController.setNewMember(_member)}" value="Edit"
						ajax="true" update="@form,:reg" />
				</p:column>

				<f:facet name="footer">
            REST URL for all members: <a
						href="#{request.contextPath}/rest/members">/rest/members</a>

				</f:facet>
			</p:dataTable>
		</h:form>
		<p>
			<a href="register.xhtml">Register a Team?</a>
		</p>
		<p>
			<a href="contestRegistration.xhtml">Register a Contest?</a>
		</p>
	</ui:define>
</ui:composition>